# Generated by Django 4.1.2 on 2022-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="recipes/images/", verbose_name="Изображение"
            ),
        )
    ]
